import React from 'react';
import { SimpleHeader } from '../SimpleHeader';

export function Terms() {
  return (
    <>
      <SimpleHeader />
      <div className="min-h-screen pt-24 pb-20 px-4 max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-8 text-zinc-900 dark:text-white">Terms of Service</h1>
        <div className="prose dark:prose-invert text-sm text-zinc-600 dark:text-zinc-400 space-y-6">
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        
        <section>
          <h2 className="text-lg font-semibold text-zinc-900 dark:text-white mb-2">1. Acceptance of Terms</h2>
          <p>By accessing and using IdeaNodes, you accept and agree to be bound by the terms and provision of this agreement.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-zinc-900 dark:text-white mb-2">2. Use License</h2>
          <p>Permission is granted to temporarily download one copy of the materials (information or software) on IdeaNodes' website for personal, non-commercial transitory viewing only.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-zinc-900 dark:text-white mb-2">3. AI Content</h2>
          <p>Content generated by our AI features is provided "as is". You retain ownership of your inputs, and we assign to you our right, title, and interest in the outputs.</p>
        </section>
        
        <section>
          <h2 className="text-lg font-semibold text-zinc-900 dark:text-white mb-2">4. Disclaimer</h2>
          <p>The materials on IdeaNodes' website are provided on an 'as is' basis. IdeaNodes makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
        </section>
      </div>
    </div>
    </>
  );
}
